### ISSUE TITLE
Not remembering saved selection when editing condition

### ISSUE THREAD

**Issue by philsward** [backdrop-contrib/field_visibility_condition#1]
Great start!

First issue to overcome: Saving the condition shows the selected field and requirement when reviewing it on the layout page, however when editing the field condition it does not remember any of the settings.

![visibility-save-problem](https://user-images.githubusercontent.com/3436110/97791461-a7de1980-1ba0-11eb-9aff-b3ea74a5c6d2.gif)

I have to wonder if this is why the condition isn't working yet.

**Comment by docwilmot** [comment]
Actually I didnt look at the negate checkbox, nor default settings. Will check this out.

**Comment by philsward** [comment]
Sounds good. I tested with and without the negate checkbox and get the same result of it not remembering what was set when editing the condition.

**Comment by docwilmot** [comment]
Hi again, added a couple changes which should help. I've ported this but TBH the usage is still a bit unclear with all the fields flying around. I would appreciate, if this still doesn't work for you, if you could do a brief step by step bullet list of how you tested, rather than a video. Maybe I could write a proper test then.

**Comment by philsward** [comment]
Ok

I'll check it out and let you know if the basic usage at least works. From
there I can start testing the more advanced aspects of how I would expect
it to work and we can tackle each one that doesn't work, in steps.

**Comment by philsward** [comment]
Just tested and looks great! Works as expected. Closing this issue as being fixed since this one is good to go.

I'll work on doing some extensive testing (as I have time) and open up issues related to each task.

Thanks for getting this started @docwilmot you're amazing :D

**Comment by docwilmot** [comment]
Great. If you could do one further favor then: you may notice the README is a bit sparse on instructions. Could you write a brief couple lines to explain how to use this please? I'll commit it to the README.
